// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: message/proto/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MSG_UNKNOWN  MsgType = 0
	MsgType_MSG_ECHO_REQ MsgType = 1001
	MsgType_MSG_ECHO_RES MsgType = 1002
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:    "MSG_UNKNOWN",
		1001: "MSG_ECHO_REQ",
		1002: "MSG_ECHO_RES",
	}
	MsgType_value = map[string]int32{
		"MSG_UNKNOWN":  0,
		"MSG_ECHO_REQ": 1001,
		"MSG_ECHO_RES": 1002,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_message_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_message_proto_message_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_message_proto_rawDescGZIP(), []int{0}
}

type EchoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EchoReq) Reset() {
	*x = EchoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReq) ProtoMessage() {}

func (x *EchoReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReq.ProtoReflect.Descriptor instead.
func (*EchoReq) Descriptor() ([]byte, []int) {
	return file_message_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *EchoReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type EchoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EchoRes) Reset() {
	*x = EchoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRes) ProtoMessage() {}

func (x *EchoRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRes.ProtoReflect.Descriptor instead.
func (*EchoRes) Descriptor() ([]byte, []int) {
	return file_message_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *EchoRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_message_proto_message_proto protoreflect.FileDescriptor

var file_message_proto_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33, 0x22, 0x1d, 0x0a, 0x07, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x1d, 0x0a, 0x07, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x2a, 0x40, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x4d, 0x53, 0x47, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f, 0x45, 0x43, 0x48, 0x4f, 0x5f, 0x52, 0x45, 0x51, 0x10, 0xe9,
	0x07, 0x12, 0x11, 0x0a, 0x0c, 0x4d, 0x53, 0x47, 0x5f, 0x45, 0x43, 0x48, 0x4f, 0x5f, 0x52, 0x45,
	0x53, 0x10, 0xea, 0x07, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_message_proto_rawDescOnce sync.Once
	file_message_proto_message_proto_rawDescData = file_message_proto_message_proto_rawDesc
)

func file_message_proto_message_proto_rawDescGZIP() []byte {
	file_message_proto_message_proto_rawDescOnce.Do(func() {
		file_message_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_message_proto_rawDescData)
	})
	return file_message_proto_message_proto_rawDescData
}

var file_message_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_message_proto_goTypes = []any{
	(MsgType)(0),    // 0: goproto.protoc.proto3.MsgType
	(*EchoReq)(nil), // 1: goproto.protoc.proto3.EchoReq
	(*EchoRes)(nil), // 2: goproto.protoc.proto3.EchoRes
}
var file_message_proto_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_message_proto_init() }
func file_message_proto_message_proto_init() {
	if File_message_proto_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EchoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EchoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_message_proto_goTypes,
		DependencyIndexes: file_message_proto_message_proto_depIdxs,
		EnumInfos:         file_message_proto_message_proto_enumTypes,
		MessageInfos:      file_message_proto_message_proto_msgTypes,
	}.Build()
	File_message_proto_message_proto = out.File
	file_message_proto_message_proto_rawDesc = nil
	file_message_proto_message_proto_goTypes = nil
	file_message_proto_message_proto_depIdxs = nil
}
